language: cpp

addons:
    apt:
        packages:
            # DepotDownloader build dependencies
            - mono-devel
            - libmono-system-core4.0-cil

            # gdc build dependencies
            - g++-multilib

install:
    # download DepotDownloader source
    - git clone https://github.com/SteamRE/DepotDownloader.git $TRAVIS_BUILD_DIR/DepotDownloader

    # import NuGet certificates
    - mozroots --sync --import

    # allow NuGet to download packages
    - export EnableNuGetPackageRestore=true

    # fix SteamKit dependency
    - sed -i 's/SteamKit2.1.6.1/SteamKit2.1.6.3/g' $TRAVIS_BUILD_DIR/DepotDownloader/DepotDownloader/DepotDownloader.csproj

    # build DepotDownloader
    - cd $TRAVIS_BUILD_DIR/DepotDownloader && .ci/build.sh

    # move DepotDownloader to main directory
    - cp $TRAVIS_BUILD_DIR/DepotDownloader/DepotDownloader/bin/Debug/DepotDownloader.exe $TRAVIS_BUILD_DIR/DepotDownloader/DepotDownloader/bin/Debug/*.dll $TRAVIS_BUILD_DIR

    # download TF2 binaries
    - mkdir $TRAVIS_BUILD_DIR/srcds && cd $TRAVIS_BUILD_DIR && mono DepotDownloader.exe -app 232250 -dir $TRAVIS_BUILD_DIR/srcds -filelist $TRAVIS_BUILD_DIR/server-binaries.txt -all-platforms

    # download SourceMod, which includes gdc
    - git clone --recursive https://github.com/alliedmodders/sourcemod.git $TRAVIS_BUILD_DIR/sourcemod

    # make sure gdc can see the SourcePawn include files
    - ln -s $TRAVIS_BUILD_DIR/sourcemod/sourcepawn/include $TRAVIS_BUILD_DIR/sourcemod/public/sourcepawn

    # properly configure gdc to build successfully
    - export CFLAGS="-Wno-unused-but-set-variable -std=c++0x"

    # build gdc
    - cd $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork && make

    # move gdc to main directory
    - cp $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork/Release/gdc $TRAVIS_BUILD_DIR

    # download CompCtrl
    - git clone https://github.com/fwdcp/CompCtrl.git $TRAVIS_BUILD_DIR/CompCtrl

script:
    # test our gamedata
    - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/srcds/bin/ ./gdc -g tf2 -e ep2v -f $TRAVIS_BUILD_DIR/CompCtrl/gamedata/compctrl.txt -b $TRAVIS_BUILD_DIR/srcds/tf/bin/server_srv.so -x $TRAVIS_BUILD_DIR/srcds/bin/engine_srv.so -w $TRAVIS_BUILD_DIR/srcds/tf/bin/server.dll -y $TRAVIS_BUILD_DIR/srcds/bin/engine.dll
