language: generic

dist: xenial

before_install:
    - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - sudo dpkg -i packages-microsoft-prod.deb
    - sudo apt-get update
    - sudo apt-get install -y apt-transport-https
    - sudo apt-get update
    - sudo apt-get install -y g++-multilib libc6-dev-i386 dotnet-sdk-2.0.0

install:
    # download DepotDownloader source
    - git clone https://github.com/SteamRE/DepotDownloader.git $TRAVIS_BUILD_DIR/DepotDownloader

    # download TF2 binaries
    - mkdir $TRAVIS_BUILD_DIR/srcds && cd $TRAVIS_BUILD_DIR && dotnet run --project $TRAVIS_BUILD_DIR/DepotDownloader/DepotDownloader/DepotDownloader.csproj -- -app 232250 -dir $TRAVIS_BUILD_DIR/srcds -filelist $TRAVIS_BUILD_DIR/server-binaries.txt -all-platforms

    # download SourceMod, which includes gdc
    - git clone --recursive https://github.com/alliedmodders/sourcemod.git $TRAVIS_BUILD_DIR/sourcemod

    # make sure gdc can see the SourcePawn include files
    - ln -s $TRAVIS_BUILD_DIR/sourcemod/sourcepawn/include $TRAVIS_BUILD_DIR/sourcemod/public/sourcepawn

    # build gdc
    - cd $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork && make

    # download CompCtrl
    - git clone https://github.com/fwdcp/CompCtrl.git $TRAVIS_BUILD_DIR/CompCtrl

script:
    # display the current version of SRCDS
    - cat $TRAVIS_BUILD_DIR/srcds/tf/steam.inf

    # test CompCtrl gamedata
    - cd $TRAVIS_BUILD_DIR && LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/srcds/bin/ $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork/Release/gdc -g tf -e ep2v -f $TRAVIS_BUILD_DIR/CompCtrl/gamedata/compctrl.txt -b $TRAVIS_BUILD_DIR/srcds/tf/bin/server_srv.so -x $TRAVIS_BUILD_DIR/srcds/bin/engine_srv.so -w $TRAVIS_BUILD_DIR/srcds/tf/bin/server.dll -y $TRAVIS_BUILD_DIR/srcds/bin/engine.dll | tee $TRAVIS_BUILD_DIR/compctrl-results.txt && ! grep -qF '! ' $TRAVIS_BUILD_DIR/compctrl-results.txt
