# since the only way to get updated Mono packages is to use Xamarin, we have to set our language differently
language: csharp

addons:
    apt:
        sources:
            # gdc build dependencies
            - ubuntu-toolchain-r-test

        packages:
            # gdc build dependencies
            - g++-5-multilib
            - linux-libc-dev:i386

install:
    # download DepotDownloader source
    - git clone https://github.com/SteamRE/DepotDownloader.git $TRAVIS_BUILD_DIR/DepotDownloader

    # restore NuGet packages
    - cd $TRAVIS_BUILD_DIR/DepotDownloader && nuget restore DepotDownloader.sln

    # build DepotDownloader
    - cd $TRAVIS_BUILD_DIR/DepotDownloader && xbuild /p:NoWarn=1584 DepotDownloader.sln /target:DepotDownloader

    # download TF2 binaries
    - mkdir $TRAVIS_BUILD_DIR/srcds && cd $TRAVIS_BUILD_DIR && mono $TRAVIS_BUILD_DIR/DepotDownloader/DepotDownloader/bin/Debug/DepotDownloader.exe -app 232250 -dir $TRAVIS_BUILD_DIR/srcds -filelist $TRAVIS_BUILD_DIR/server-binaries.txt -all-platforms

    # download SourceMod, which includes gdc
    - git clone --recursive https://github.com/alliedmodders/sourcemod.git $TRAVIS_BUILD_DIR/sourcemod

    # make sure gdc can see the SourcePawn include files
    - ln -s $TRAVIS_BUILD_DIR/sourcemod/sourcepawn/include $TRAVIS_BUILD_DIR/sourcemod/public/sourcepawn

    # build gdc
    - cd $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork && make CPP='gcc-5'

    # download CompCtrl
    - git clone https://github.com/fwdcp/CompCtrl.git $TRAVIS_BUILD_DIR/CompCtrl

script:
    # display the current version of SRCDS
    - cat $TRAVIS_BUILD_DIR/srcds/tf/steam.inf

    # test CompCtrl gamedata
    - cd $TRAVIS_BUILD_DIR && LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/srcds/bin/ $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork/Release/gdc -g tf -e ep2v -f $TRAVIS_BUILD_DIR/CompCtrl/gamedata/compctrl.txt -b $TRAVIS_BUILD_DIR/srcds/tf/bin/server_srv.so -x $TRAVIS_BUILD_DIR/srcds/bin/engine_srv.so -w $TRAVIS_BUILD_DIR/srcds/tf/bin/server.dll -y $TRAVIS_BUILD_DIR/srcds/bin/engine.dll | tee $TRAVIS_BUILD_DIR/compctrl-results.txt && ! grep -qF '! ' $TRAVIS_BUILD_DIR/compctrl-results.txt
