language: cpp

addons:
    apt:
        packages:
            - g++-multilib

install:
    - git clone --recursive https://github.com/alliedmodders/sourcemod.git $TRAVIS_BUILD_DIR/sourcemod
    - ln -s $TRAVIS_BUILD_DIR/sourcemod/sourcepawn/include $TRAVIS_BUILD_DIR/sourcemod/public/sourcepawn    # make sure gdc can see the SourcePawn include files
    - export CFLAGS="-Wno-unused-but-set-variable -std=c++0x"                                               # properly configure gdc to build successfully
    - cd $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork && make
