language: cpp

addons:
    apt:
        packages:
            # DepotDownloader build dependencies
            - mono-devel
            - libmono-system-core4.0-cil

            # gdc build dependencies
            - g++-multilib

install:
    # download DepotDownloader source
    - git clone https://github.com/SteamRE/DepotDownloader.git $TRAVIS_BUILD_DIR/DepotDownloader

    # allow NuGet to download packages
    - export EnableNuGetPackageRestore=true

    # fix SteamKit dependency
    - sed -i 's/SteamKit2.1.6.1/SteamKit2.1.6.3/g' $TRAVIS_BUILD_DIR/DepotDownloader/DepotDownloader/DepotDownloader.csproj

    # build DepotDownloader
    - cd $TRAVIS_BUILD_DIR/DepotDownloader && .ci/build.sh

    # download SourceMod, which includes gdc
    - git clone --recursive https://github.com/alliedmodders/sourcemod.git $TRAVIS_BUILD_DIR/sourcemod

    # make sure gdc can see the SourcePawn include files
    - ln -s $TRAVIS_BUILD_DIR/sourcemod/sourcepawn/include $TRAVIS_BUILD_DIR/sourcemod/public/sourcepawn

    # properly configure gdc to build successfully
    - export CFLAGS="-Wno-unused-but-set-variable -std=c++0x"

    # build gdc
    - cd $TRAVIS_BUILD_DIR/sourcemod/tools/gdc-psyfork && make
